name: Build

on:
  push:

jobs:
  linux-x86:
    name: linux-x86
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build
        run: nix-build
  windows-x86:
    name: windows-x86
    runs-on: windows-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Set up MingGW
        uses: egor-tensin/setup-mingw@v2
      - name: Download Raylib
        run: |
          curl -L https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_win64_mingw-w64.zip -o raylib.zip
          7z x raylib.zip -oraylib
          rm raylib.zip
      - name: Build
        run: |
          gcc --version
          export RAYLIB_PATH=$(pwd)/raylib/raylib-5.0_win64_mingw-w64
          make CC=gcc build

